package com.test.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.test.greendao.db.User1;

import com.test.greendao.db.User1Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig user1DaoConfig;

    private final User1Dao user1Dao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        user1DaoConfig = daoConfigMap.get(User1Dao.class).clone();
        user1DaoConfig.initIdentityScope(type);

        user1Dao = new User1Dao(user1DaoConfig, this);

        registerDao(User1.class, user1Dao);
    }
    
    public void clear() {
        user1DaoConfig.clearIdentityScope();
    }

    public User1Dao getUser1Dao() {
        return user1Dao;
    }

}
