package com.test.greendao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER1".
*/
public class User1Dao extends AbstractDao<User1, Long> {

    public static final String TABLENAME = "USER1";

    /**
     * Properties of entity User1.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property User_id = new Property(1, int.class, "user_id", false, "USER_ID");
        public final static Property Address = new Property(2, String.class, "address", false, "ADDRESS");
        public final static Property Headicon = new Property(3, String.class, "headicon", false, "HEADICON");
        public final static Property Last_name = new Property(4, String.class, "last_name", false, "LAST_NAME");
        public final static Property First_name = new Property(5, String.class, "first_name", false, "FIRST_NAME");
        public final static Property Email = new Property(6, String.class, "email", false, "EMAIL");
    }


    public User1Dao(DaoConfig config) {
        super(config);
    }
    
    public User1Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER1\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: user_id
                "\"ADDRESS\" TEXT," + // 2: address
                "\"HEADICON\" TEXT," + // 3: headicon
                "\"LAST_NAME\" TEXT," + // 4: last_name
                "\"FIRST_NAME\" TEXT," + // 5: first_name
                "\"EMAIL\" TEXT);"); // 6: email
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER1\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User1 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUser_id());
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(3, address);
        }
 
        String headicon = entity.getHeadicon();
        if (headicon != null) {
            stmt.bindString(4, headicon);
        }
 
        String last_name = entity.getLast_name();
        if (last_name != null) {
            stmt.bindString(5, last_name);
        }
 
        String first_name = entity.getFirst_name();
        if (first_name != null) {
            stmt.bindString(6, first_name);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(7, email);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User1 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUser_id());
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(3, address);
        }
 
        String headicon = entity.getHeadicon();
        if (headicon != null) {
            stmt.bindString(4, headicon);
        }
 
        String last_name = entity.getLast_name();
        if (last_name != null) {
            stmt.bindString(5, last_name);
        }
 
        String first_name = entity.getFirst_name();
        if (first_name != null) {
            stmt.bindString(6, first_name);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(7, email);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public User1 readEntity(Cursor cursor, int offset) {
        User1 entity = new User1( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // user_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // address
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // headicon
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // last_name
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // first_name
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // email
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User1 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUser_id(cursor.getInt(offset + 1));
        entity.setAddress(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHeadicon(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLast_name(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFirst_name(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setEmail(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(User1 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(User1 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User1 entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
